<head>
<meta charset='UTF-8' />
<meta name='viewport' content='width=device-width, initial-scale=1' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/gh/nhab/nhab@latest/assets/css/blocks.css'>
<script src='https://cdn.jsdelivr.net/gh/nhab/nhab@latest/assets/js/blocks.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js'></script>
<script src='https://code.jquery.com/jquery-3.6.3.min.js'></script>
</head>
<body onload='AddToggleButtons();ReplaceLtGt();hljs.highlightAll();'>
 <button onclick="toggleAll(this);" >-</button>
 <h2>References</h2>
<div>
<p>
 Revit:
	http://designbuildacademy.com/wp-content/uploads/2015/10/REVIT_Walkthrough_getting-Started.pdf
	https://www.autodesk.com/learn/ondemand/curated/revit-quick-start-guide/7zaNxjrGOCJLyGe8bK7MMs
	
 Revit Api:
	https://www.revitapidocs.com/2022/
	https://www.revitapidocs.com/code/
 </p>
</div>
 <h2>Revit Fundemental concepts</h2>
 <div>
 <p>
 <b>Revit</b>
	Revit is a design and documentation platform 
	that supports the design, drawings, and schedules 
	required for <b> building information modeling (BIM)</b>. 

	BIM delivers information about project design, scope, quantities, and phases when you need it.

<b>Types of Elements</b>
	1- model elements
	2- datum elements
	3- view-specific elements. 

<b>Model elements</b>
	- Elements in Revit are also referred to as families. 
	- The family contains the geometric definition of the element 
	   and the parameters used by the element. 

	- Each instance of an element is defined and controlled by the family.
	- Model elements represent the actual 3D geometry of the building. 
	 They display in relevant views of the model.

Examples:
	- Hosts elements, like     : Walls, Ceilings, Floor and roofs
	- Model components, like   : doors,Windows,Stairs,Furniture
	- Structured elements like : Beams,Structural columns,Structural walls, Isolated footings,3D rebar
	- MEP Elements like        : Pipes , Ducts,Sprinklers,Air terminals
	- other: slabs, and ramps,Sinks, boilers, ducts, sprinklers, and electrical panels

Types of model elements:
	1- Hosts (or host elements) are generally built in place at the construction site.
		Example : Walls and ceilings,Structural walls and roofs
	2- Model components are all the other types of elements in the building model.

<b>Datum elements</b>
	 help to define project context. 
	 examples:
	 grids, levels, and reference planes are datum elements.

<b>View-specific elements</b>
	 display only in the views in which they are placed. 
	 They help to describe or document the model. 
	 example:
	 dimensions 

Types of view-specific elements:
	 <b>Annotation elements</b> are 2D components that document the model and maintain scale on paper. 
		For example, dimensions, tags, and keynotes are annotation elements.
	 <b>Details</b> are 2D items that provide details about the building model in a particular view.
 		Examples include detail lines, filled regions, and 2D detail components.

<b>Element Properties</b>
	Each element you place in a drawing is an instance of a family type. 
	Elements have 2 sets of properties that control their appearance and behavior: 
	type properties 
	and instance properties.

<b>Type Properties</b>
	The same set of type properties is common to all elements in a family,
	 and each property has the same value for all instances of a particular family type.

	For example, all elements that belong to the Desk family have a Width property, 
	but its value varies according to family type.
	 Thus every instance of the 60 x 30-inch family type (1525 x 762 mm) within the Desk family has a Width value of 60 inches (1525 mm), 
	 while every instance of the 72 x 36-inch family type (1830 x 915 mm) has a Width value of 72 inches (1830 mm).

	Changing the value of a type property affects all current and future instances of that family type.

<b>Instance Properties</b>
	A common set of instance properties also applies to all elements that belong to a particular family type,
	 but the values of these properties may vary according to the location of an element in a building or project.

	For example, the dimensions of a window are type properties, while its elevation from the level is an instance property. 
	Similarly, cross-sectional dimensions of a beam are type properties, while beam length is an instance property.

	Changing the value of an instance property affects only the elements in your selection set, 
	or the element that you are about to place. 
	For example, if you select a beam, and change one of its instance property values on the Properties palette,
	 only that beam is affected. If you select a tool for placing beams,
	 and change one of its instance property values, 
	 the new value applies to all beams you place with that tool.
 
<b> Project:</b>
	 In Revit, the project is the single database of information for your design—the building
	information model. The project file contains all information for the building design, from geometry to
	construction data. This information includes components used to design the model, views of the
	project, and drawings of the design. By using a single project file, Revit makes it easy for you to alter
	the design and have changes reflected in all associated areas (plan views, elevation views, section
	views, schedules, and so forth). Having only one file to track also makes it easier to manage the
	project.

<b>Level:</b>
	 Levels are infinite horizontal planes that act as a reference for level-hosted elements, such as
	roofs, floors, and ceilings. Most often, you use levels to define a vertical height or story within a
	building. You create a level for each known story or other needed reference of the building; for
	example, first floor, top of wall, or bottom of foundation. To place levels, you must be in a section or
	elevation view.

<b>Element: </b>
	When creating a project, you add Revit parametric building elements to the design. Revit
	classifies elements by categories, families, and types.

<b>Category:</b>
	 A category is a group of elements that you use to model or document a building design.
	For example, categories of model elements include walls and beams. Categories of annotation
	elements include tags and text notes.

<b>Family:</b>
	 Families are classes of elements in a category. A family groups elements with a common set
	of parameters (properties), identical use, and similar graphical representation. Different elements in a
	family may have different values for some or all properties, but the set of properties—their names and
	meaning -- is the same. For example, 6-panel colonial doors could be considered one family,
	although the doors that compose the family come in different sizes and materials.

<b>families Types</b>:
	 Loadable families 
		can be loaded into a project and created from family templates. 
		You can determine the set of properties and the graphical representation of the family.
	 System families 
		include walls, dimensions, ceilings, roofs, floors, and levels. 
		They are not available for loading or creating as separate files.
		 Revit predefines the set of properties and the graphical representation of system families.
		 You can use the predefined types to generate new types that belong to this family within the project.
			For example, the behavior of a wall is predefined in the system. However,
			you can create different types of walls with different compositions.
		 System families can be transferred between projects.
	 In-place families are custom families that you create in the context of a project.
	   Create an in-place family when your project needs unique geometry 
	   that you do not expect to reuse or geometry that must maintain one of more relationships to other project geometry.
		 Because in-place families are intended for limited use in a project, each in-place family contains only a single type. \
		You can create multiple in-place families in your projects, and you can place copies of the same in-place family element in your projects. 
		Unlike system and standard component families, you cannot duplicate in-place family types to create multiple types.

	Type: Each family can have several types.
	 A type can be a specific size of a family, such as a 30‖ X42‖ title block or a 32" x 84" door. 
	 A type can also be a style, such as default aligned or default angular style for dimensions.

	Instance: Instances are the actual items (individual elements) that are placed in the project and have
	specific locations in the building (model instances) or on a drawing sheet (annotation instances).
<b>Elavations</b>
	- elevations are views that show the vertical faces of a building or object. 
	- They are typically used to show the exterior faces of a building,
	 but can also be used to show the interior faces of a room or space. 
	
Elevation levels: 
	 are used to define the height of a building or object above a reference point.
	 They can be edited in the Properties palette or directly in the level tag

Elevation base: 
	 is the datum that Revit uses to display the elevation of a level. 
	 It can be set to either the project base point or the survey point

Display of levels: 
	 The display of levels in Revit is controlled in a similar way to grids. 
	 Use 2D and 3D extents to adjust how datums are displayed in the views of your Revit project

Interior elevations:
	 Interior elevations are views that show the vertical faces of a room or space. 
	 They are typically used to show details such as finishes, cabinetry, and fixtures

Drafting standards:
	 Drafting standards for interior elevations vary depending on the firm and the project. 
	 They are typically drawn to scale, with the limits of the ceiling, floor, and adjacent walls shown with a dark outline

<b>Revit menu(Ribbons)</b>
Revit consist of these ribons:
	
	- Architechture Ribbon:
		Modify,Wall, Door, Window,Component,column,Roof,Ceiling,Floor,Curtain System, Curtain Grdi
		Mullion,Railing,Ramp, Stair 
	
	- Structure Ribbion
		Modify,Beam,Wall,Column,Floor,Truss,Brace,Beam system,Isolated,Wall,Slab,Rebar,Area,Path,Fabric Area,fabric sheet,Cover
		
	- Systes Ribbons
		Modify,Duct,Duct placeholder, Flex duct,Air terminal, Mechanical equipment,pipe,pipe placeholder, parallel pipes,pumping fixture,spirinkler
		Wire,Cable Tray,
	
	-Insert Ribbon
		Modify,Link revit,link IFC, Link CAD DWF Markup
		
<b>The View Cube</b>
You can click and drag the ViewCube to reorient the view of a model to a custom viewpoint
 or click on one of the twenty-six predefined viewpoints that are available. 
 As you drag, the mouse pointer changes
 to indicate that you are reorienting the current view of the model. 
 
 If you drag the ViewCube close to one of the preset orientations and it is set to snap to the closest view, 
 the ViewCube rotates  to the closest preset orientation.

<b>The Steering Wheel</b>
Pressing and dragging on a wedge of a wheel is the primary mode of interaction. 
After a wheel is displayed, click one of the wedges and hold down the button on the pointing device 
to activate the navigation tool.
 Drag to reorient the current view. 
 Releasing the button returns you to the wheel.
 
 <b>Navigation Bar</b>
You can control which navigation tools are displayed on the navigation bar with the Customize menu.
The Customize menu is displayed by clicking the Customize button.
 From the Customize menu, you click the navigation tools that you want displayed on the navigation bar.
 The position of the navigation tools on the navigation bar is predefined and cannot be changed.
 
 <b>Creating a Project</b>
	 1) Launch the Autodesk® Revit® application.
	2) Click ► New ► PROJECT.
	3) In the New Project dialog box, under Create New, verify that Project is selected.
	4) Under Template file, verify the second option is selected, and click BROWSE.
	5) Verify C:\ProgramData\Autodesk\RVT 2015\Templates\US Imperial \default.rte
	[DefaultMetric.rte] is selected, and click OPEN.
	6) In the New Project dialog box, click OK.

<b>Create levels in the building</b>
	1) Enter ZO to zoom out.
	2) Click Architecture tab ► Datum panel ► LEVEL.
	3) On the Draw panel, click PICK LINES.
	4) On the Options Bar enter 10 [3000 mm] for the Offset.
	5) In the drawing area, highlight the 01 Lower Level line; when a dashed line is displayed
	above the level line, click to create a level (Level 3).
	6) Using the same method, create a level above Level 3.
	7) On the Panel Level tab, click MODIFY to end the command.
	8) Rename the new levels and all corresponding views:
	 Level 3: Rename as 02 Entry Level
	 Level 4: Rename as 03 Roof
	9) Double-click the level dimensions, and enter new values:
	 0' 0'' [0 mm]: Change to -14' 0'' [-5250 mm]
	 10' 0'' [4000 mm]: Change to -10' 0'' [-3050 mm]
	 20' 0'' [7000 mm]: Change to 0' 0'' [0 mm]
	 30' 0'' [10000 mm]: Change to 10' 0'' [3050 mm]
	10) Press ESC twice to deselect and exit command.
	11) Save the project file

<b> Create walls</b>
	1) In Project Browser, under Floor Plans, double-click 00 Foundation to open that view in the drawing area.
	2) Click Architecture tab ► Build panel ► WALL.
	3) In Properties palette ► Change Element Type drop-down and select Basic Wall:
	Retaining - 12'' Concrete [Basic Wall : Retaining - 300mm Concrete].
	4) On the Options Bar below the tool ribbon:
		 For Height, select 02 Entry Level.
		 For Location Line, verify that Wall Centerline is selected.
		 Verify that Chain is selected.
	5) In the drawing area, draw walls on the foundation level:
		 Click in the lower-right quadrant to select the wall start point.
		 Move the cursor to the left, enter 40' [12000 mm], and press ENTER.
		NOTE: You do not need to specify the unit; Autodesk® Revit® software uses the
		units specified in the project template.
		 Beginning at the new endpoint, move the cursor up, enter 22' [6900 mm], and press
		ENTER.
		 Move the cursor to the right, enter 40' [12000 mm], and press ENTER.
	6) On the Modify | Place Wall tab, click MODIFY to exit the command.
	7) In Project Browser, under Floor Plans, double-click 01 Lower Level.
	8) Click Architecture tab ► Build panel ► WALL.
	9) In Properties palette ► Change Element Type drop-down and select Basic Wall:
		Foundation - 12'' Concrete [Basic Wall : Foundation - 300mm Concrete].
	10) On the Options Bar, for Depth, select 00 Foundation and for Location Line, 
		verify that Wall Centerline is selected.
	11) Draw walls on the lower level:
		 In the drawing area, click the right endpoint of the south wall as the wall start point.
		 Move the cursor to the right, enter 6' 6'' [1950 mm], and press ENTER.
		 Move the cursor up, enter 5' [1500 mm], and press ENTER.
		 Move the cursor to the right, enter 10' 6'' [3150 mm], and press ENTER.
		 Move the cursor up, and select the intersection with the extension of the north wall
	 Select the right endpoint of the north wall to complete the chain and connect the walls.
	12) On the Place Wall panel, click MODIFY.
	13) Save the project file.

<b>Creating terrain</b>
	1) In Project Browser, under Floor Plans, double-click 02 Entry Level.
	2) Create a 3D view:
	 Click the View tab ► Create panel ► 3D View drop-down ► CAMERA.
	 Click in the upper-right corner of the drawing area to place the camera.
	Click to place the camera target point
	A 3D view is created. The view you create may differ slightly from the illustrations shown
	in the exercises because of minor variations in camera placement. Drag the blue circular
	controls that display on the crop region of the resulting view so that you can see the
	building.
	3) In Project Browser, expand 3D Views, right-click 3D View 1, and click RENAME.
	4) In the Rename View dialog box, enter To Building, and click OK.
	5) Create a graded building site:
		 In Project Browser, under Floor Plans, double-click Site.
		 Click Massing & Site tab ► Model Site panel ► TOPOSURFACE.
		 On the Options Bar, for Elevation, enter -0' 6'' [-150 mm].
		 Add points to the left of the building, as shown. The order of the point selection is not important.
		On the Options Bar, for Elevation, enter -10' [-4000 mm].
		Add points near the center of the building, as shown. Contour lines are displayed.
		On the Options Bar, for Elevation, enter -11' [-4300 mm].
		 Add points to the right of the building, as shown.
		 Click Edit Surface tab ► Surface panel ► FINISH SURFACE.
	6) Create a pad surface:
		 Click Massing & Site tab ► Model Site panel ► BUILDING PAD.
		 On the Draw panel, click RECTANGLE.
		 Select the outer endpoint at the lower left of the building, as shown.
		 Select the outer endpoint at the upper right of the building.
		 On the Create Pad Boundary tab, in the Building Pad panel, click FINISH EDIT MODE.
	7) Open the To Building 3D view to see the results.
	8) Save the project file. In this exercise, you created a simple toposurface in Autodesk Revit
	by selecting points.
	However, for most projects, complex site models created by civil engineering
	professionals will be provided to you in DWG, DXF, DGN, or point files. You can import
	these files into your Revit project where you can automatically generate a terrain using
	the Toposurface tool.
 </p>
</div>

<h2>Revit API</h2>
<div>
<p>
<b>Hello World Sample plugin .net framework 4.7</b>

1- Create new project:
	Run Visual Studio Community 2019 → File → New → Project → Class Library (.NET Framework)
	
2- Add References:
	Right click “References“ under Solution Explorer → Add Reference → 
	Browse → “C:\Program Files\Autodesk\Revit 2019 “ → Add “RevitAPI” & “RevitAPIUI” → Select “RevitAPI“ & “RevitAPIUI“ → Properties → Copy Local → False
	
3- Add Namespaces
	using Autodesk.Revit.Attributes;
	using Autodesk.Revit.DB;
	using Autodesk.Revit.UI;
	
4- Implement IExternalCommand
	public class Class1:IExternalCommand 

5-	Execute Method
	public class class1:IExternalCommand 
	{
		public Result Execute(...)
		{
			TaskDialog.Show("Title", "Hello World!");
			return Result.Succeed;
		}
	}
	
6-Build → Build Solution

7- Create “.Addin” file
	Right click “MyFirstRevitPlugin” file → Add → New item → Application Manifest File → File name “MyFirstRevitPlugin.addin”
	
8- Configure “.Addin” file & Re-build

9-Configure ".Addin" file and Re-build 
</p>
	<pre><code>
	<?xml version="1.0" encoding="utf-8"?>
	<RevitAddIns>
	  <AddIn Type="Command">
		<Name>MyFirstRevitPlugin</Name>
		<FullClassName>MyFirstRevitPlugin.Class1</FullClassName>
		<Text> Hello World Text </Text>
		<Description> Hello World Description</Description>
		<VisibilityMode>AlwaysVisible</VisibilityMode>
		<Assembly>
		  C:\Users\junha\source\repos\MyFirstRevitPlugin\MyFirstRevitPlugin\bin\Debug\MyFirstRevitPlugin.dll
		</Assembly>
		<AddInId>502fe383-2648-4e98-adf8-5e6047f9dc34</AddInId>
		<VendorId>AECTechy</VendorId>
		<VendorDescription>AECTechy</VendorDescription>
	  </AddIn>
	</RevitAddIns>
	</code></pre>
<p>
	Replace the <Assembly> portion with your directory output from Step 9
	Set “Copy to Output Directory” property of the .Addin file to “Copy if newer”.

10- Copy addin file to Revit addin directory
	 if you installed Revit with default folder location:
	 All users
	C:\Program Files\Autodesk\Revit 2019\AddIns
	Individual user
	C:\Users\<Your User Name>\AppData\Roaming\Autodesk\Revit\Addins\2019
	Go to directory from Step 9 → Copy “MyFirstRevitPlugin.addin”
	→ Paste into ” C:\Users\<Your User Name>\AppData\Roaming\Autodesk\Revit\Addins\2019″
	
11-Run your first addin!
	Run Revit 2019 → Load the Addin → Add-ins tab→ External tools → Run “Hello World!”
</p>
</div>
